### ISSUE TITLE
As a user I want to sign into other platforms

### ISSUE THREAD

**Issue by smashedlife** [revelation/ember-admin#31]
Rails API Endpoint
- [x] Api endpoint to authenticate against Librarian and Decipher. (exists in older api)

Ember
- [x] Build the action to link to endpoint.

**Comment by zulaica** [comment]
Is platform authentication handled solely by sso_controller or am I missing something elsewhere?

**Comment by smashedlife** [comment]
For the JWT stuff, that is correct.



Jonathan So

Director of Engineering
Phone:   +1 203-428-2466 Ext. 2466

FocusVision |  www.focusvision.com<http://www.focusvision.com>
Find us on:  Twitter<https://twitter.com/FocusVisionInfo> | Facebook<https://www.facebook.com/FocusVisionWW> | LinkedIn<https://www.linkedin.com/company/focusvision?trk=company_logo> | GooglePlus<https://plus.google.com/+Focusvision/posts>
