### ISSUE TITLE
As a user I want to access the Settings Dropdown

### ISSUE THREAD

**Issue by smashedlife** [revelation/ember-admin#37]
- [ ] In ember we need a new ember route to project/#/messages/digest/settings
- [x] In ember we need rails routes for Projects, Segments, Terms (Fixed in #44)
- [ ] In ember we need to display a digest settings page.

**Comment by zulaica** [comment]
@kscherling: The current messages route is not nested within the project. In our meeting we discussed making digests a type of message. Are we good to nest messages within project?

**Comment by zulaica** [comment]
Nesting the routes winds up incorrectly affecting inheritance when it comes to settings. The current setup route works best. The better solution would be to set up the relationship between messages and digests in the model.
